language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  email: pcu.consortium@gmail.com
  name: Travis CI
  local_dir: _site
  target_branch: master
  on:
    branch: src-pages
branches:
  only:
  - src-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: eAaOnr9K9oFxOkgm6V+cEAhTwP7UqIRjw1wdVF+o9UsGsvPqdYogNiKzECeY2HCgvfY8GvxMoUtslihy5DvipHJLgWfs08ojJyh2I4x4TMuPrKaSv+xyMxTiMUatscRb87k28eRFRE7+ifuqrwBRalxMqsGvllrOTyx6vOdozLmjT8Fx/jz2NmB/ktqzSwc6fP2l4dETW8DPYOaCnTfWepnmwGIBzw9Zs1ZCDECubbR7MGFBPMXnjw2I6zKyRnaZZ/CO+G94Dr17PHNKfDY4QxC517Kut74GdBqZaAYvqHb52F4qpNcmIMTzPuIQSJT8tYkieEXu/jM5eCEFYhaYv3VDo5gHsjI0caHnhXoQcNuLRZCkIBlu0BKEYOn2WCEIEobl8LJ7kHdxZHfte/2c8DXWXPiTeAbcUMMb+0r3ik7C9GTucrh5DX5P/p22mDvGQ0m2msgNwLFRWWNs7ukA+ZNyWY47cL8Jh4PY/h3glnEaGOgYrQJ/mD+Ktem4pntT9FkQXD/NXIVziSc0aXhP/L1Ohh8JPSZuKa3NL2yD0sAR5BtfKhfcpPAH8/56K/vzKcejISoD0hE07dzLAlnSBeAtJmYr51OYazlm5yEd0gjQ/MRhJcWSoKOX3QUsO0FHG6TDkmRC1OduFLj+yKSJZ/vElH20vIN4p/nJzJkUB5A=
sudo: false
