language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: gh-pages
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: eeHx2mjtnIR91zHqKlsPxwtiEP5v0BE4JO2G3kSN26qi+09MMV3fBYFce8hLwVRD/gj+PCU5mZ/gsiJf8jL5AUFYyMo4Y0XBJQVwqMd71LCjtEsoPRlBIkiCclV1Ulxg6E7NQ4XT0WJGjy/piMgLyagyem0Yg0oFvd+HgM84Pef8cIh2wu2ptzEzc4vKzdO+4jtvSG0kWHm0uBA1rwIlgaTWNY7KSZCyZ9KtNlwRLN19URGPQu4DupgJyaj2dY2UVnxhREWIy6JLOVnc2UclgKrL5Q+uoAYQOsnj4iZrTuP1MQV+vzbl5xNpI1KMfSsKZEbuiZA4oqGMHBivp8ttuwDE82ZoOxefp5MyzR3GudFJSTzDEcBkrgBKnG/AbxNMJ6BjjzOggalaxnbIdMq3X7jJ0JczrBefW0fOe6WmfyTlRuIzYTFYUs6PadpNfFGw05VxPL/BJnOvEq/VZmjO44pmeT9l7FpoO1pqolqJ5U3hEYjeyKyMlWo0IrFFLwSg80sUgwK1gv5FzQhKYR3OAt3e4FNetsSL7xRbWp9OSSiWs00rnsDVofj71Ekgl0uCEC/s1wDW1tM/F7nhDr7XSrDqBACjEqOrUgErNNwoz+GNC33UvaH5AmsNDk8TtxwkCtcxLThVDz32S9fYN3JxuEg5teGuxVjqU2Q2nl6pvWY=
sudo: false
