language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  email: pcu.consortium@gmail.com
  name: Travis CI
  on:
    branch: master
branches:
  only:
  - src-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: gVECbd9mTQgMG/HA1PhPY2Dbh1wbLkB+6HlFbwVuoBATDe7rg9zUDa/IKsnMIHrhx2pFz/n0Rj7eQbDvTG9ESy+1rDQTLxRFHU2c6LZsZvZhmuG7kGFw5+ZnMyLjQ7lMOsh85BRLuDvCpp/mHYhrmkXXq7Z8ycVSEhpsG00szWTalDd8Ozmy9KrkmygNATATmM07g2ZIOYOb92IZtfxlo6lAl0+PIDn4iMW0lr8XjBbw1vE+10XEQqDmEfKEfHbss5lmciUYb2FAd6Tg6xMdCIH2o99+LO3gwyCMZsvxk9NAzQJ83CskInXNe8hasZelCBMKIEWSuwi3RNk1QNSOho3UVUvWZ98877wUgoYqHlXlRfqgXXeQN2tsuB6z+yv0Bm1cr+l9+EHIPj7/EFv5lCRXqNgvzJKMeOsVKCFXTFw/7vi2HmI1a+y0lcBGGiiYETR9h2RSt+NBtChj8XYt3fR+r5jU/O7Rdpl2VA3KlvHVTcoVHn4tlfWgI7QTeIJNwrg9W6F/I5fu5HkHyyDmtGLLfYUvKNEnkUQQln2ZYVPFiGxUD0fh0sKpvHXvZwVpDnBfjIT9q/J/1yjmunId0ohhMEY8sk6Q3VRPaTyD0VsHqnWGT/y5ir0AUsgc+PsA7YIQTITvHkc9dmHCD90O7+PWNwdQHgRP+hK7R+iAjrw=
sudo: false
