#general
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pcu-consortium.github.io" # the base hostname & protocol for your site
permalink: /news/:year/:title/
paginate: 5
paginate_path: "/news/:num/"
lang: fr_FR
jekyll-mentions:
  base_url: https://twitter.com

#tags
tag_page_layout: news
tag_page_dir: tag
tag_permalink_style: pretty
tag_page_data:
  sitemap: false

# seo
title: PCU
email: pcu-drive@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Unified Knowledge Platform
author:
  name: PCU Consortium
social:
  name: PCU Consortium
  links:
    - https://twitter.com/pcu2017
    - https://github.com/pcu

#social media
twitter_username: PCUConsortium
github_username: pcu-consortium
facebook_username: pcu-consortium
linkedin_username: pcu-consortium
slideshare_username: pcuconsortium

#nav
nav:
  - title: Overview
    url: /overview
  - title: Use Cases
    url: /use-cases
  - title: Resources
    url: /resources
  - title: News
    url: /news
  - title: Community
    url: /community

aboutNav:
  - title: Brand Guideline
    url: /brand-guideline
  - title: Terms of use
    url: /terms-of-use

#collections
collections:
- community
- use-cases

# Build settings
asciidoc:
  attributes:
    source-highlighter: pygments
    pygments-css: class
    pygments-stylesheet: asciidoc-pygments.css
asciidoctor:
  safe: unsafe
  attributes:
    - icons=font
timezone: Europe/Paris
encoding: utf-8
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .gitignore
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor
